root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = ["tmp", "prints"]
  include_ext = ["go", "tpl", "tmpl", "html", "hbs", "css", "js"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false

[misc]
clean_on_exit = true
